### ISSUE TITLE
关于metrics文件缺失，能否恳请博主分享一下这个文件？

### ISSUE THREAD

**Issue by tom155680** [lzjjeff/HGraph-CL#1]
博主您好，我最近关注到您写的HGraph-CL这个代码，感觉您写的非常好，但是我在下载后发现里面缺少一个metrics文件，from metrics import mosei_metrics, mosei_metrics_with_zero，关于这个指标文件，因为您写好的metrics文件肯定与您当前的代码契合度更高，能否恳请您分享一下这个文件？万分感激不尽

**Comment by lzjjeff** [comment]
感谢对本工作的关注以及指出这个问题！缺少的文件已经上传
